### ISSUE TITLE
Can't drag Map Stack

### ISSUE THREAD

**Issue by almccon** [stamen/maps.stamen.com#104]
In the editor window, I can click and drag on the map to view other locations.

The cursor turns into a text cursor, so is there some kind of text overlay that's now intercepting clicks, when it didn't previously?

![mapstack_drag](https://user-images.githubusercontent.com/1212178/28046932-f7dca9ce-659b-11e7-84cd-100ae1feca3a.gif)

**Comment by almccon** [comment]
Workaround: 

Navigate to the right spot using maps.stamen.com, and then copy the zoom and coordinates from that URL and paste it into the mapstack URL.

For example this: 
http://maps.stamen.com/toner/#12/51.5096/-0.0991

And then replace the end of the mapstack url so it looks like this:

http://mapstack.stamen.com/edit.html#watercolor/12/51.5096/-0.0991

**Comment by sconnelley** [comment]
I am getting these console error's.
![image](https://user-images.githubusercontent.com/565486/28077102-bf762b26-662e-11e7-8639-987ad2beb1ab.png)
