### ISSUE TITLE
how can download image from maps.stamen.com

### ISSUE THREAD

**Issue by greencomputinguae** [stamen/maps.stamen.com#108]
I have developed a function which download image in png and jpg formats from the google map. However, when I want to use that function to download the map from maps.stamen.com with format, it does not work by my previous Matlab code

http://tile.stamen.com/toner/{z}/{x}/{y}.png
http://tile.stamen.com/terrain/{z}/{x}/{y}.jpg
http://tile.stamen.com/watercolor/{z}/{x}/{y}.jpg

My Matlab code is showing in the following:

```
url = [preamble location zoomStr sizeStr maptypeStr styles format markers labelsStr languageStr sensor keyStr path];

% Get the image
try
    urlwrite(url,filename);
catch % error downloading map
    warning(sprintf(['Unable to download map form Google Servers.\n' ...
        'Possible reasons: no network connection, quota exceeded, or some other error.\n' ...
        'Consider using an API key if quota problems persist.\n\n' ...
        'To debug, try pasting the following URL in your browser, which may result in a more informative error:\n%s'], url));
    varargout{1} = [];
    varargout{2} = [];
    varargout{3} = [];
    return
end
```

Actually,  the following url is not valid !!!

http://tile.stamen.com/toner/12/23/31.png

**Comment by almccon** [comment]
Hi @greencomputinguae, sorry I just noticed this issue now. Is the URL http://tile.stamen.com/toner/12/23/31.png still not working for you? It works for me.
