### ISSUE TITLE
S3 permission denied for images.m2i.stamen.com bucket?

### ISSUE THREAD

**Issue by timstallmann** [stamen/maps.stamen.com#111]
Hi -- not sure if this is the right place, but I couldn't find a Map 2 Image repository to report this. Just logged on this AM and S3 is giving a "Permission denied" error on images in the images.m2i.stamen.com bucket, thus breaking the whole m2i service -- e.g. https://s3.amazonaws.com/images.m2i.stamen.com/20171016/mapstack_D57CDjmtWT4.png

Anyone know what's up?

**Comment by elizasususweet** [comment]
I'm wondering the same thing.
