### ISSUE TITLE
Replace Mapzen geocoder with something else.

### ISSUE THREAD

**Issue by almccon** [stamen/maps.stamen.com#115]
Recommendations for migration: https://mapzen.com/blog/migration/

[Nominatim](http://nominatim.openstreetmap.org/)
[OpenCage Data](https://geocoder.opencagedata.com/)
[OSMNames](https://osmnames.org/)
[Mapbox Search API](https://www.mapbox.com/geocoding/)

**Comment by almccon** [comment]
Looks like I'm using Nominatim in my side-by-side viewer, so why not try that? https://github.com/stamen/side-by-side

**Comment by loganwilliams** [comment]
fixed
