### ISSUE TITLE
Missing tiles

### ISSUE THREAD

**Issue by ehdonovan** [stamen/maps.stamen.com#118]
Discovered a few missing tiles today in the Cape Canaveral Florida area:
http://stamen-tiles-c.a.ssl.fastly.net/terrain/14/4522/6836.png
http://stamen-tiles-d.a.ssl.fastly.net/terrain/14/4522/6837.png
http://stamen-tiles-a.a.ssl.fastly.net/terrain/14/4521/6835.png

url in code: 'http://stamen-tiles-{s}.a.ssl.fastly.net/terrain/{z}/{x}/{y}.{ext}

Error: 
404 Not Found
    Code: NoSuchKey
    Message: The specified key does not exist.
    Key: terrain/14/4522/6836.png
    RequestId: DFAFA1E87B641F4E

Thanks for providing such a great basemap!

![image](https://user-images.githubusercontent.com/6217873/35242831-cc4cebc0-ff88-11e7-9c12-514749d268aa.png)

**Comment by loganwilliams** [comment]
dupe #107
