### ISSUE TITLE
Search is not working

### ISSUE THREAD

**Issue by elizasususweet** [stamen/maps.stamen.com#121]
When I enter a city name in to the search box I get the following response "Sorry, we couldn't find 'city name'.

**Comment by almccon** [comment]
Sorry about that, this is likely due to the face that Mapzen went out of business. We were using their free geocoding service. See #115. 

We will replace the geocoder soon, so that search functionality will start working again. 

Thanks for letting us know!

**Comment by grayspark** [comment]
Any news on this? Search is still not working!! Help :(

**Comment by fblackbu** [comment]
Same! I thought it was because I didn't donate, so I donated and still cannot search! Please help!

**Comment by loganwilliams** [comment]
fixed

**Comment by elizasususweet** [comment]
I saw that! Thank you!
________________________________

**Comment by i0nkol** [comment]
> fixed

Doesn't work now
