### ISSUE TITLE
Cannot find any locations

### ISSUE THREAD

**Issue by fblackbu** [stamen/maps.stamen.com#122]
Overtime I search a location it will say it isn't found. 
<img width="1268" alt="screen shot 2018-03-07 at 9 40 47 am" src="https://user-images.githubusercontent.com/37149106/37098333-a3dbe38c-21eb-11e8-9a51-d203b8c408e3.png">

**Comment by fblackbu** [comment]
every time**

**Comment by sherrydramsey** [comment]
Has this ever been addressed? I have the same issue. No city I enter can ever be found, even ones I know I accessed in the past.

**Comment by loganwilliams** [comment]
fixed
