### ISSUE TITLE
migrate website resources to HTTPS

### ISSUE THREAD

**Issue by nekromoff** [stamen/maps.stamen.com#123]
Since many websites are already on HTTPS and this year more will migrate, you should allow connecting to your map resources via HTTPS instead of providing insecure connection / invalid certificate.

Let's Encrypt is easy.

**Comment by davidessayan** [comment]
I have exactly the same request.
Because we have to turn SSL on for SEO reasons, it would be awesome to have tiles delivered via HTTPS.

**Comment by almccon** [comment]
To get HTTPS tiles, you can load them directly from Fastly. Basically, replace `http://{s}.tile.stamen.com` with `https://stamen-tiles-{S}.a.ssl.fastly.net`, or replace `http://tile.stamen.com` with `https://stamen-tiles.a.ssl.fastly.net`.

If you need protocol-agnostic URLs, use //stamen-tiles-{s}.a.ssl.fastly.net/, as that endpoint will work for both SSL and non-SSL connections.
