### ISSUE TITLE
No Australia

### ISSUE THREAD

**Issue by Fifty22** [stamen/maps.stamen.com#128]
Hi,
I've always used this amazing site, but now that I need a map from a part of Brisbane, in Australia, the website didn't produce anything. I left the processing of the image all night long but didn't happened.
![cattura](https://user-images.githubusercontent.com/44665058/47839718-6c68b300-ddff-11e8-8de3-57b11e1a97d0.JPG)

Just trying, I've used the same layers in another place in the word, and then voilà, the site produce me the image.
![mapstack_j61_2gsdkbq](https://user-images.githubusercontent.com/44665058/47839720-725e9400-ddff-11e8-8c54-23a1dc0461e0.png)

Please, someone, help me!

**Comment by loganwilliams** [comment]
fixed
