### ISSUE TITLE
data not loading correctly in terrain at high zoom level

### ISSUE THREAD

**Issue by jinniking** [stamen/maps.stamen.com#131]
Hi,

I'm looking for a map as at: http://maps.stamen.com/#terrain/14/50.3853/-3.8903

The terrain map is loading well in places, but some areas are blank. toner and watercolour seem ok but i'd prefer terrain if possible.

![2018-12-06 1](https://user-images.githubusercontent.com/45670863/49608442-8d896a00-f990-11e8-84ac-90b2dc5276ab.png)
![2018-12-06 4](https://user-images.githubusercontent.com/45670863/49608443-8e220080-f990-11e8-8268-fad2044d2a5f.png)

**Comment by loganwilliams** [comment]
dupe #107
