### ISSUE TITLE
Terrain map has bad labels and also completely different from toner labels

### ISSUE THREAD

**Issue by enorazza** [stamen/maps.stamen.com#141]
The issue is clear by just looking at the home page website:
![image](https://user-images.githubusercontent.com/9676092/58874667-b08ba100-86c9-11e9-844d-9e9660c08e2b.png)

The "toner labels" map shows a very consistent set of labels, in particularly focused to show countries name, capitals, big cities, sea names.  

Instead the "terrain" map has **very** strange labels:
- Capitals are completely gone. Where is Rome?
- Useless smaller cities appear and the text is UPPERCASE without a logical reason.   
- Too many mount names.  
- No sea names.  

Solution proposed: replace the terrain labels with the toner labels

**Comment by loganwilliams** [comment]
Closed, won't fix. Use the terrain background map if you want to overlay your own labels.
