### ISSUE TITLE
Tiles not loading in Chrome

### ISSUE THREAD

**Issue by stevenpaulr** [stamen/maps.stamen.com#167]
Website works fine in Edge and Safari, but the tiles do not load in chrome.

[https://wyotelassn.org/broadband-overview-page/](https://wyotelassn.org/broadband-overview-page/)

**Comment by almccon** [comment]
I think this is the known problem that we do not support HTTPS at the tile.stamen.com URL. To use HTTPS, you need to load our tiles directly from our CDN Fastly. So instead of `http://tile.stamen.com`, you use `https://stamen-tiles-{S}.a.ssl.fastly.net`. You can scroll down to the bottom of the page at http://maps.stamen.com/ for more info.

Let us know if this doesn't solve your problem.

**Comment by stevenpaulr** [comment]
I'm already using the SSL from Fastly

`function radmap_enqueue(){
    wp_enqueue_style( 'Leaflet', "https://unpkg.com/leaflet@1.6.0/dist/leaflet.css" );
    wp_enqueue_style( 'RadMapStyle', plugins_url("radmap.css", __FILE__));
    wp_enqueue_script( 'Leaflet', 'https://unpkg.com/leaflet@1.6.0/dist/leaflet.js', array(), '1.6.0');
    wp_enqueue_script( 'Stamen', "https://stamen-maps.a.ssl.fastly.net/js/tile.stamen.js?v1.3.0");`

**Comment by ebrelsford** [comment]
@stevenpaulr The site is loading tiles from `https://*.tile.stamen.com/...` which is not the correct domain:

![image](https://user-images.githubusercontent.com/375002/105881531-a3c06d00-5fd2-11eb-93a1-e02f096de8a5.png)

You're best off using a [Leaflet tileLayer](https://leafletjs.com/reference-1.7.1.html#tilelayer) with the proper domain name: `https://stamen-tiles.a.ssl.fastly.net/terrain/{z}/{x}/{y}.jpg`, for example.

**Comment by stevenpaulr** [comment]
Awesome, I replaced:
`var layer = new L.StamenTileLayer(\"terrain\");`
with
`var layer = new L.tileLayer('https://stamen-tiles.a.ssl.fastly.net/terrain/{z}/{x}/{y}.jpg');`
and it solved my problem. It would be nice if the version of the javascript hosted on the SSL CDN would reference the SSL CDN version of the tiles. Thanks for the help.
