### ISSUE TITLE
Watercolor image tiles are not loaded because of SSL cert error

### ISSUE THREAD

**Issue by FridaNyvall** [stamen/maps.stamen.com#168]
Watercolor image tiles are not loaded because of SSL cert error:
![image](https://user-images.githubusercontent.com/25387271/106297544-1d668e00-6253-11eb-8a57-855705d4b2c3.png)
![image](https://user-images.githubusercontent.com/25387271/106297567-22c3d880-6253-11eb-9e05-04b811083c02.png)
Example link to image tile: [https://d.tile.stamen.com/watercolor/15/17987/9541.jpg](https://d.tile.stamen.com/watercolor/15/17987/9541.jpg)

**Comment by FridaNyvall** [comment]
For anyone else having this problem: Found a workaround for this by switching the start of the URL to https://stamen-tiles-d.a.ssl.fastly.net/watercolor.

**Comment by almccon** [comment]
Correct, we do not support SSL on the tile.stamen.com endpoint, only using the fastly URLs.
