### ISSUE TITLE
"Read about it" link for toner map is password protected

### ISSUE THREAD

**Issue by karlb** [stamen/maps.stamen.com#169]
The "Read about it" link for the toner map on http://maps.stamen.com/#toner/ links to http://content.stamen.com/dotspotting_toner_cartography_available_for_download, which seems to be protected by HTTP basic authentication. I assume that this is not intended.

**Comment by almccon** [comment]
Good catch. The updated link for that blog post is now this: https://hi.stamen.com/dotspottings-toner-cartography-available-for-download-1f652eb25f38

**Comment by almccon** [comment]
Fixed by #174
