### ISSUE TITLE
Service Unavailable / SSL invalid

### ISSUE THREAD

**Issue by davidvlasic** [stamen/maps.stamen.com#171]
It looks like the endpoints are returning a Service Unavailable error

https://stamen-tiles.a.ssl.fastly.net/js/tile.stamen.js

and we're getting invalid SSL cert errors for the tiles
<img width="599" alt="Screen Shot 2021-04-30 at 2 23 10 pm" src="https://user-images.githubusercontent.com/19275989/116648172-b9717400-a9bf-11eb-8bb6-01e70f996621.png">

**Comment by almccon** [comment]
Oh, sorry, it's a bit confusing but the javascript comes from `stamen-maps.a.ssl.fastly.net` while the tiles come from `stamen-tiles.a.ssl.fastly.net`.  Note `maps` vs `tiles` in the url.

The full path to the js library is: https://stamen-maps.a.ssl.fastly.net/js/tile.stamen.js
