### ISSUE TITLE
Making an atlas not working

### ISSUE THREAD

**Issue by lauracf94** [stamen/maps.stamen.com#172]
Hi everyone
I'm trying to make an atlas as usual and this issue appears when I click Make an Atlas 

"We're sorry, but something went wrong.
If you are the application owner check the logs for more information."

I have tried from differents explorers and the bug stays.

I would need to print maps today as late cause tomorrow I will be on field mapping the whole day. Please, reach me out when bug is fixed - lauracf94@gmaill.com

Thanks

**Comment by almccon** [comment]
Hi Laura, we rebooted the servers a few hours later and everything works now. We replied to you via email.
