### ISSUE TITLE
Feedback Form - broken link

### ISSUE THREAD

**Issue by george08** [stamen/maps.stamen.com#18]
Some of the help emails I get don't have the map-type stamped in the URL.

Like, 
http://maps.stamen.com//#12/37.7706/-122.3782
http://maps.stamen.com/????????/#12/37.7706/-122.3782

From there, I can't tell which map style they're talking about unless they say something specific.

E.g.

---
Bug report from anonymous (67.186.132.2):

	looking great

http://maps.stamen.com//#12/37.7706/-122.3782

-- 
feedback form @ http://maps.stamen.com/feedback.php

---

**Comment by emilyhobson** [comment]
Replace and point to: https://github.com/stamen/maps.stamen.com/issues/new

**Comment by sconnelley** [comment]
Here's what I have right now.  @ericrodenbeck @mojodna @almccon -- could use some copy 

![image](https://cloud.githubusercontent.com/assets/565486/16742501/e4473b12-4775-11e6-9ea1-b3be4598e53a.png)

**Comment by almccon** [comment]
Oops, we also need this for the fullscreen map pages. Any idea if that's easy to do?

**Comment by almccon** [comment]
And I think @sconnelley's copy is great! But we should remove the "See here for more info" that links to http://citytracking.org/some-known-bugs-and-whats-to-do/. That page is too old.

**Comment by almccon** [comment]
I removed the link to the old citytracking blog post, and I change the feedback form on all the fullscreen map pages to use the "create a new issue" approach. For the toner and terrain variants it directs the user to create an issue in the relevant repo. For the other map styles, it sends them to this repo (maps.stamen.com).

So the old feedback form is finally dead!
