### ISSUE TITLE
Burkina Faso misspelled

### ISSUE THREAD

**Issue by AlexanderRayCarlson** [stamen/maps.stamen.com#189]
I was playing a tutorial on Command: Modern Operations and noticed this:

Looks like Burkina Faso has a typo.

![image](https://user-images.githubusercontent.com/15145538/153823474-72f17306-308e-415b-90ad-7af0e332424a.png)

Visible here: http://maps.stamen.com/terrain-labels/#6/13.154/-1.165

**Comment by almccon** [comment]
Thanks for spotting that. We already have that issue tracked in another repository over here: https://github.com/stamen/toner-carto/issues/75. I'm going to close this issue as a duplicate so we aren't tracking the problem in two places.

Unfortunately, we have no timeline for fixing the bug. Here's what I wrote over in the other issue:

> Looks like this is an error in a very old copy of Natural Earth, which has been fixed long ago. I'll fix the data file but we don't have any immediate plans to update the rendered map tiles. It might be months or years before we regenerate the tiles again. 😞
