### ISSUE TITLE
HTTPS Certificate Issue

### ISSUE THREAD

**Issue by przybang** [stamen/maps.stamen.com#191]
Our map instance is now displaying multiple console errors related to the tile.stamen.com URL.  Inspecting the certificate in Chrome indicates that it is invalid.

tile.stamen.com/terrain-labels/4/4/4.jpg:1          GET https://tile.stamen.com/terrain-labels/4/4/4.jpg net::ERR_CERT_COMMON_NAME_INVALID

**Comment by ebrelsford** [comment]
This is a known issue. See the bottom of [maps.stamen.com](http://maps.stamen.com):

> Instead of using our JavaScript library, you can refer to the tile URLs directly.
>
> Many applications and libraries understand the notion of map URL templates. These are ours:
>
>    https://stamen-tiles.a.ssl.fastly.net/toner/{z}/{x}/{y}.png
>    https://stamen-tiles.a.ssl.fastly.net/terrain/{z}/{x}/{y}.jpg
>    https://stamen-tiles.a.ssl.fastly.net/watercolor/{z}/{x}/{y}.jpg
>
> Multiple subdomains can be also be used: https://stamen-tiles-{S}.a.ssl.fastly.net
