### ISSUE TITLE
Certificate error leading to lost tiles

### ISSUE THREAD

**Issue by njakeman** [stamen/maps.stamen.com#207]
MS Edge is seeing the tile URL (e.g. https://a.tile.stamen.com/toner/12/2049/1362.png) as not secure.
Please could you check your certificates are up to date?

**Comment by almccon** [comment]
Hello @njakeman.

We have never supported HTTPS on the `*.tile.stamen.com` URLs (we created this service long before HTTPS was common). Instead, for the past few years you were able to use Fastly URLs to get HTTPS (see previously closed issues like https://github.com/stamen/maps.stamen.com/issues/191).

However, right now we are in the process of partnering with Stadia Maps to move our basemaps to new infrastructure, which means that the URLs will be changing again. Right now, you can start using Stadia URLs to get HTTPS, such as this: https://tiles.stadiamaps.com/tiles/stamen_toner/12/2049/1362.png. Soon these URLs will require an API key, but during the transition they do not. For more information about the transition to Stadia, see here: http://maps.stamen.com/stadia-partnership/

Can I ask, are you using these tiles in an application you are developing, or did you see these certificate errors on someone else's website that uses our tiles? If it was on someone else's website, we'd like to know who it is so we can reach out to them and let them know they need to update their URLs. Thanks!
