### ISSUE TITLE
Watercolor - Issue recurrently reported, left unanswered: tiles grey when loading, becoming grey when zooming … 

### ISSUE THREAD

**Issue by sloyen** [stamen/maps.stamen.com#208]
I have chosen Stamen Watercolor as the default map for a small collaborative project in the field of genetic genealogy because the design is gorgeous and its simplicity well suited to the project's purpose.

I use online services provided by Gogocarto. So I reported the problem to them a few months ago.  They responded that everything is OK on their side and the issue should come from the tiles server.

Last week, the entire map remained grey. Today, certain tiles are grey and the whole map becomes grey when zooming.

No problem with other maps displayed instead ...

URL@https://bretagnel21.gogocarto.fr
<img width="2048" alt="1-Capture d’écran 2023-07-13 à 08 25 25" src="https://github.com/stamen/maps.stamen.com/assets/123085708/59a2ab48-affc-4f12-ad79-064dd21d7f9b">
<img width="2048" alt="2-Capture d’écran 2023-07-13 à 08 25 54" src="https://github.com/stamen/maps.stamen.com/assets/123085708/bc336e49-b6e9-4e67-9821-55a1a34ab5af">
<img width="2048" alt="3-Capture d’écran 2023-07-13 à 16 12 42" src="https://github.com/stamen/maps.stamen.com/assets/123085708/16c69164-da9d-4195-9855-4f0104e86897">
<img width="2048" alt="4-Capture d’écran 2023-07-13 à 16 12 58" src="https://github.com/stamen/maps.stamen.com/assets/123085708/3c67e499-66ac-4f84-a4e4-2ac0c9439880">
<img width="2048" alt="Capture d’écran 2023-07-14 à 19 36 27" src="https://github.com/stamen/maps.stamen.com/assets/123085708/b418c570-262f-4f3b-963f-cda8d92be804">

Any comments are welcome.

**Comment by akshatpunia26** [comment]
+1 on this, I am just trying to zoom in and encountering grey tiles after a while. Not even the same for the three options shown. [Link](http://maps.stamen.com/#terrain/15/28.5690/77.5652)<img width="1482" alt="Screenshot 2023-07-19 at 5 26 04 AM" src="https://github.com/stamen/maps.stamen.com/assets/92669600/2a3b7f4d-35bc-41b1-8d6a-2491b5b54535">

**Comment by almccon** [comment]
Thanks for the bug report @sloyen. You've spotted a particular problem with gogocarto.fr where they are requesting `.png` files when watercolor only supports `.jpg` files. Stamen recently made a change where we were previously allowing the incorrect png requests, but now we are not. We will follow up with the maintainers of gogocarto.fr and help them make a fix. That will explain why you suddenly are getting all-gray maps for watercolor.

As for the additional report from @akshatpunia26, it is true that for all of our map styles, if you zoom in far enough you might see missing tiles. This has been a known issue for many years. We are right now in the process of partnering with Stadia Maps to update these maps, so in the coming months we  will be able to fix the problem of broken tiles. We will be posting more on this page as we have more updates: http://maps.stamen.com/stadia-partnership/

**Comment by sloyen** [comment]
Excellent!  Thanks again.

Sylvain Loyen

**Comment by akshatpunia26** [comment]
thnx for the clarification
