### ISSUE TITLE
Stamen Watercolor

### ISSUE THREAD

**Issue by dequavious** [stamen/maps.stamen.com#212]
**Describe the bug**
The "Stamen Watercolor" tile is no longer loading for my folium map. Other tiles still work fine.

**Screenshots**
![Screenshot from 2023-11-04 13-42-15](https://github.com/stamen/maps.stamen.com/assets/89927358/dd0c9d6e-63fe-4201-b727-fb209c72f193)

**Comment by gitressa** [comment]
See https://github.com/stamen/maps.stamen.com.

**Comment by almccon** [comment]
Yes, the Stamen Fastly URLs no longer work as of October 31st. Our tiles have migrated to Stadia Maps, so you need to create an account on Stadia and update your URLs to continue using our tiles. Documentation is here: https://docs.stadiamaps.com/guides/migrating-from-stamen-map-tiles/
