### ISSUE TITLE
Migrate to Leaflet

### ISSUE THREAD

**Issue by sethfitz** [stamen/maps.stamen.com#56]
Potential plugins to use to achieve the picture-in-picture effect:

https://github.com/bbecquet/Leaflet.MagnifyingGlass - seems to allow fixed coordinates, but not fixed window locations
https://github.com/turban/Leaflet.Sync - used for MapStack, but unclear how to initially correctly align the inner windows

**Comment by JLuc** [comment]
It seems the new leaflet version automaticaly request retina version when it thinks it's required... but there is no watercolor retina display version 

![previously shown](https://cloud.githubusercontent.com/assets/565486/5131351/e970ab02-70bf-11e4-9f82-51a5f5e14e84.png)


So what about watercolor @2x version ?

**Comment by almccon** [comment]
@JLuc thanks for this feedback. We have no plans to produce a retina version of watercolor. Maybe there is some other workaround here?

**Comment by JLuc** [comment]
Ok i'll see.
Is watercolor the only one missing retina  or do some other stamen layers not provide retina tiles ?
