### ISSUE TITLE
Google Maps support broken

### ISSUE THREAD

**Issue by infn8** [stamen/maps.stamen.com#69]
I have the following code:
```html
<script src="https://maps.googleapis.com/maps/api/js?v=3.exp"></script>
<script>
	var map;
	function initialize() {
		var mapOptions = {
			zoom: 15,
			disableDefaultUI: true,
			center: new google.maps.LatLng(43.680386, -79.391536)
		};
		map = new google.maps.Map(document.getElementById('my-map'),
			mapOptions);
	}
	google.maps.event.addDomListener(window, 'load', initialize);
</script>
```
and that works great but adding the stamen library after the google one causes a JS error
```html
<script src="https://maps.googleapis.com/maps/api/js?v=3.exp"></script>
<script type="text/javascript" src="http://maps.stamen.com/js/tile.stamen.js"></script>
<script>
	var map;
	function initialize() {
		var mapOptions = {
			zoom: 15,
			disableDefaultUI: true,
			center: new google.maps.LatLng(43.680386, -79.391536)
		};
		map = new google.maps.Map(document.getElementById('my-map'),
			mapOptions);
	}
	google.maps.event.addDomListener(window, 'load', initialize);
</script>
```
the error comes out as ```TypeError: a is Undefined -> https://maps.gstatic.com/maps-api-v3/api/js/21/2/main.js (line 12, col 257)``` 

Let me know if you need more info

**Comment by infn8** [comment]
This is also broken on the stamen google maps example

http://maps.stamen.com/test/google.html

**Comment by mojodna** [comment]
@sconnelley can you have a look at this when you get a chance?

**Comment by sconnelley** [comment]
@infn8 -- Sorry took so long to get around to this.  The file `tile.stamen.js` should be fixed now.  Let me know if you are still seeing an errors.

**Comment by infn8** [comment]
@sconnelley no worries.  You guys are the ones doing us the service so thanks for all that you do get to.  It looks good so far.  I'll open another issue if i see anything during re implementation.  in the downtime I switched to a styled google map.  But it's looking good on your [demo page](http://maps.stamen.com/test/google.html) and [in the wild](http://www.ocadu.ca/) as well
