### ISSUE TITLE
Shouldn't your https endpoint serve the https url for the maps?

### ISSUE THREAD

**Issue by deweydb** [stamen/maps.stamen.com#70]
https://stamen-maps.a.ssl.fastly.net/js/tile.stamen.js?v1.3.0

gives the tile url as:
http://{S}tile.stamen.com/

so things still break.

I downloaded the script and load it locally so i could edit this line to:
            "url":          ["https://stamen-tiles.a.ssl.fastly.net/", layer, "/{Z}/{X}/{Y}.", type].join(""),

**Comment by mojodna** [comment]
We don't really support `tile.stamen.js`, so you're probably better off either instantiating appropriate layers directly in your mapping library of choice or by using https://github.com/leaflet-extras/leaflet-providers.

**Comment by deweydb** [comment]
I'm confused, i found this all from your homepage, if it isn't supported why is it on your homepage in the documentation section?

**Comment by mojodna** [comment]
Because we haven't updated the homepage in ages (perils of a consulting company). Thanks for the nudge.

**Comment by deweydb** [comment]
i know that feel bro.
