### ISSUE TITLE
Copyright entity is messed up

### ISSUE THREAD

**Issue by almccon** [stamen/maps.stamen.com#72]
075a81e20ec4d919d9788891d3a1218d0f241f0e ought to be doing the right thing, but there's something going wrong:

![screen shot 2016-07-09 at 9 jul 10 39 04](https://cloud.githubusercontent.com/assets/1212178/16709304/9502dd32-45c1-11e6-91d0-1d88757347cb.png)

**Comment by mojodna** [comment]
I haven't actually pushed that commit yet.

**Comment by mojodna** [comment]
Pushed this morning.
