### ISSUE TITLE
Can't find by GPS coordinates

### ISSUE THREAD

**Issue by brunetton** [stamen/maps.stamen.com#80]
Hi all, I wanted to export a portion of map for printing. But there's not address indexed in OSM around this place. So I have to find by GPS coords ("xx.xxxxx, yy.yyyyy")

**Comment by clhenrick** [comment]
@brunetton you can go to a location using latitude and longitude by altering the URL hash, for example: 
```
http://maps.stamen.com/#terrain/12/40.7238/-74.0024
```

**Comment by brunetton** [comment]
Thanks for your answer.
Yes I noticed that, but this is not really accessible to everybody. Gps
coordinates are a standard supported nearly everywhere in mapping software,
it's quite surprising that an open project don't support it.
Interoperability - which is so precious to open software - is kind of
broken here, isn't it ?

**Comment by clhenrick** [comment]
The search by location uses Mapzen's geocoding service which is meant for geocoding places, not latitude longitude coordinates. Sorry but we don't have the capacity to implement lat lon searching on maps.stamen.com.

**Comment by almccon** [comment]
@brunetton In the spirit of open source software, we try to re-use existing open source tools and platforms wherever possible, instead of re-inventing the wheel. That's why we use the Mapzen geocoder. If you wish, you can open an issue there: https://github.com/mapzen/leaflet-geocoder/issues

If the Mapzen geocoder starts to support GPS coordinates, then that will benefit many other open source webmaps, not just the ones on maps.stamen.com.

**Comment by brunetton** [comment]
Hi Alan, thanks for answering.
Your choice is of course totaly righteous. Coding a geocoding engine is a
really hudge task, and trying to re inventing the wheel is totally out of
the question.
I didn't check which is the behavior of Nominatim for gps coordinates, but
Pelias (geocoder developed and used by Mapzen) acts like every geocoders :
trying to decode a "human" address to long / lat. Maybe it makes sense that
it doesn't recognize gps coordinates, as it is not really "human" notation.

Maybe could we just make a simple regexp filter that checks for gps
coordinates forms and in this case doesn't call Pelias service ? (as
there's no job to do, nothing to decode)

Thanks for reading
