### ISSUE TITLE
MapStack not loading

### ISSUE THREAD

**Issue by dikembe3000** [stamen/maps.stamen.com#85]
The map stop loading when you add a second layer. We are using five layers for a class assignment with about 20 people using it at once. Two students were able to export their image before it stopped working.

**Comment by almccon** [comment]
Thanks, it seems to be working again. I haven't seen this problem happen before, but maybe we've never had 20 people all trying to make a similar map at the same time.

If it's still happening, or if it happens again, could you paste the URL into this issue so we can just to see exactly which layers are failing? 

You can paste either the "edit" link that's in your browser window: http://mapstack.stamen.com/edit.html#watercolor;mapbox-water[tint=$ff6600@100]/11/37.7544/-122.3513

...or you can right-click in the map area and select "copy image address" which will give you the url of that map tile, like this: http://c.sm.mapstack.stamen.com/(watercolor,(mapbox-water,$ff6600[hsl-color]))/11/327/791.png

**Comment by dikembe3000** [comment]
Awesome, Thanks Alan.,
