### ISSUE TITLE
heads up, tile server is being flaky.

### ISSUE THREAD

**Issue by Yermo** [stamen/maps.stamen.com#86]
It looks like the tile server is having an issue.

This issue can be seen on the main site: http://maps.stamen.com/terrain/#12/37.7706/-122.3782

Load it. Zoom in or out. Note that not all tiles render.

(at least as of 2017-02-28 14:52 EST). 

I'm running on Chrome under Linux but I strongly suspect it's a server side issue. 

This started earlier today.

**Comment by almccon** [comment]
A lot of our tile infrastructure is hosted on Amazon Web Services, and they are having a serious outage today: https://www.theregister.co.uk/2017/02/28/aws_is_awol_as_s3_goes_haywire

Not much we can do about it at the moment. Everything _should_ come back to life once AWS is working again.

**Comment by Yermo** [comment]
Thank you for the reply! 

I sincerely appreciate the effort you guys put in to making these tile servers available. I was just reporting it on the extreme off chance that you were not aware. 

Thanks again.
