### ISSUE TITLE
Https certificates expired

### ISSUE THREAD

**Issue by Ryan-Sharp** [stamen/maps.stamen.com#87]
It appears that some of the certificates for at least some of the tile hosting sites have expired. I have included screenshots of what this behavior looks like, what the error looks like, and a snip of Digicert's tool for checking web site certificates. It leads to issues when getting the map tiles using https rather than http. This was observed on the Terrain map, but I don't know if it is more widespread than that.

Cheers,
Ryan

Appearance of unloaded tiles: 

![image](https://cloud.githubusercontent.com/assets/26725090/24377645/0bc8eb36-130e-11e7-8c1b-3cc1c04b5b29.png)

Errors in the console:

![image](https://cloud.githubusercontent.com/assets/26725090/24377671/1edb2b8a-130e-11e7-8ab4-b9ab9c7a8264.png)

Digicert's tool for checking web site certificates:

![image](https://cloud.githubusercontent.com/assets/26725090/24459843/7afa4024-146a-11e7-8428-07306a439fab.png)

**Comment by TobiasBales** [comment]
Any update on this?
Would be great to at least have some feedback

**Comment by dg0yal** [comment]
We're also encountering this.

**Comment by sconnelley** [comment]
The certificates have been restored.  Thanks for your patience.
