### ISSUE TITLE
Some areas of US incompatible with Map>Image, but only at certain zoom settings

### ISSUE THREAD

**Issue by ozenHaqadosh** [stamen/maps.stamen.com#88]
I'm trying to create some images of a highway in Wyoming at the default zoom, but for whatever reason the images fail to process past a certain point (specifically, going east past around Green River on the I-80). It's worth mentioning that the images I'm taking are rather large (2000x1294), but when I capture an image of the same area on the map in that resolution but zoomed out a fair bit, it works fine, and I haven't had problems with any other areas on the map. It's only once you past this certain point on the map and are zoomed in to the default zoom that the images fail to process. I've gone a little farther down the highway and had the same problem, though I'm not sure how far it goes. Also, I tried zooming out and shrinking the capture area to create the same image, but the same thing happens if you're zoomed in too far. It also happens regardless of map style (I tried them all).

Here's the area I'm referring to: http://maps.stamen.com/m2i/#terrain/2000:1294/12/41.7692/-107.5616

Any reason why this may be happening?

**Comment by ozenHaqadosh** [comment]
Update: I went down the highway, capturing images as I went, and it finally started processing images at this point:

http://maps.stamen.com/m2i/image/20170404/terrain_rGCAzANyZS4

For whatever reason, the whole east half of Wyoming and overwhelming majority of Nebraska failed to produce a single image.

**Comment by sconnelley** [comment]
The issue was the SSL certificates had expired.  We have restored the certificates and the tiles are flowing :-)
