### ISSUE TITLE
Algeria spelled wrong on terrain map at zoom level 4

### ISSUE THREAD

**Issue by Ryan-Sharp** [stamen/maps.stamen.com#89]
See screenshot below

![image](https://cloud.githubusercontent.com/assets/26725090/24624940/59ddfc36-187b-11e7-9732-fc03fb3a5f0c.png)

**Comment by almccon** [comment]
Thanks @Ryan-Sharp! I filed an issue over on the Terrain Classic repo: https://github.com/stamen/terrain-classic/issues/102 which is where we will have to make the fix. I'm not sure when we will have time to fix this and redeploy... might be several months. Let us know if you catch any similar errors!
