### ISSUE TITLE
Blank tiles at high zoom levels

### ISSUE THREAD

**Issue by Yermo** [stamen/maps.stamen.com#91]
At high zoom levels for many areas in the US, notably around the Smokey Mountains National Park, blank tiles are generated using the Terrain style.

This can be easily seen here on the maps.stamen.com site:

http://maps.stamen.com/terrain/#18/35.47397/-83.92101

Some tiles are correctly generated. 

![2017-04-24-130607_1920x1054_scrot](https://cloud.githubusercontent.com/assets/854565/25349204/f67d2548-28ee-11e7-8a0a-2052bcd67500.png)

**Comment by sconnelley** [comment]
The issue was expired SSL certificates.  The certificates have been restored and tiles are flowing :-)

**Comment by Yermo** [comment]
Thank you!

Where can I ask "help" type questions? (e.g. i'd like to put together a docker instance of the stack necessary to generate and server these classic terrain tiles ...)
