### ISSUE TITLE
Ross Creek, Townsville QLD not showing on Stamen Watercolour

### ISSUE THREAD

**Issue by malleeblue** [stamen/maps.stamen.com#92]
Hi, On the watercolour version of Townsville, Ross Creek does not go any further inland than the bridge at Stanley St. In the Toner Lite version it does.
Can this be fixed for the watercolour version? 

I am using QGIS 2.18 and the Quick Map Services plugin to get the Stamen Watercolour.
![toner lite](https://cloud.githubusercontent.com/assets/10095503/25562060/64be315e-2dbe-11e7-8d13-7642e88e775f.png)
![watercolour](https://cloud.githubusercontent.com/assets/10095503/25562061/64eaec9e-2dbe-11e7-97fe-a66baeff2895.png)

I have attached screen shots.

http://maps.stamen.com/watercolor/#15/-19.2604/146.8238

**Comment by almccon** [comment]
Hi @malleechick, 

Unfortunately Watercolor uses a very old copy of the OpenStreetMap database, and we don't have an easy way to update it at the moment. So any errors or missing data that was in OSM at the time is more or less permanently stuck in our Watercolor maps. Someday hopefully we will update the data, but we don't have any current timeline for doing so. 

Sorry about that!

**Comment by malleechick** [comment]
Thanks for letting me know. I'll see what I can do with Paint.net to fix the gap.
