### ISSUE TITLE
Error Loading Images

### ISSUE THREAD

**Issue by Sven74Muc** [stamen/maps.stamen.com#93]
I get very often the "error: map images could not be load" if I zoom into a map quickly or into a higher zoom level.

https://demo.mapsmarker.com/maps/fullscreen/layer/12/
Switch to Stamen Terrain in the upper right menue and see it happens

**Comment by Sven74Muc** [comment]
Any idea?

**Comment by sconnelley** [comment]
The issue was the SSL certificates had expired.  We have restored the certificates and the tiles are flowing :-)
