### ISSUE TITLE
Certificate and tile generation error

### ISSUE THREAD

**Issue by IhmeHippi** [stamen/maps.stamen.com#94]
Downloading tiles, especially ones at higher zoom levels, fail with SSL errors - specifically certificate expiry. If the SSL error is ignored, the request ends up failing nonetheless.

An illustrative example:
Downloading tile from: http://tile.stamen.com/terrain/12/2318/1622.png
Redirects to (e.g.): https://a.dyn.tile.stamen.com/r/terrain/12/2318/1622.png
This connection fails with an SSL Certificate Expired error.
If error ignored, redirects further to (e.g.): http://b.b.tile.stamen.com/terrain/12/2318/1622.png
This returns a NoSuchKey error.

This is most likely a duplicate of issue #87, and probably also issues #88, #91, and #93.

**Comment by sconnelley** [comment]
Certificates have been restored, thanks for your patience.
