### ISSUE TITLE
Terrain & Terrain-Classic not working

### ISSUE THREAD

**Issue by 9littlebees** [stamen/maps.stamen.com#95]
I can make a JPEG map in watercolour, and a PNG map in toner, but the site won't let me create a map in the terrain or terrain-classic modes.  It creates a link to a new map, but when you go to that link, it says "Sorry, your image could not be made. REMAKE MAP".  When I click on the REMAKE MAP link, it still fails, saying: "Sorry. Your map can't be made at the moment. Please try again in a little bit."  I have waited a long time and retried, but it doesn't remake the map properly.

Main link is here: [maps.stamen.com/m2i/#terrain-classic/2000:1450/12/52.2704/8.9737](http://maps.stamen.com/m2i/#terrain-classic/2000:1450/12/52.2704/8.9737)

And the created map is here: [maps.stamen.com/m2i/image/20170503/terrain-classic_4Llu-bBjl-Q](http://maps.stamen.com/m2i/image/20170503/terrain-classic_4Llu-bBjl-Q)

**Comment by liberrybooked** [comment]
Having the same problem with terrain-lines.

My main link is here: http://maps.stamen.com/m2i/#terrain-lines/2000:1500/15/39.9647/-75.1420
My created map should be here: http://maps.stamen.com/m2i/image/20170511/terrain-lines_zlTe97k7p10

**Comment by sconnelley** [comment]
Terrain tiles were down due to expired SSL certificates.  We have restored them and the tiles are rendering again.  I am not sure why the "REMAKE MAP" link is not working.  But I would suggest starting over from the beginning.

**Comment by iosdevelop** [comment]
I noticed that the Neatline dependency on Stamen maps have this bug.  It seems their SSL is still expired why tiles are not loading when forced to use SSL.  The tiles will load without SSL but most browsers have improved security with mixed content warnings.   

Error:
•	Firefox Developer Edition detected a potential security threat and did not continue to c.tile.stamen.com.

Fix:  I’ve added manually the https.  Click on each link in your respect browsers and accept SSL_ERROR_BAD_CERT_DOMAIN or your connection is not private then continue.  

[https://c.tile.stamen.com/terrain/13/4305/2931.jpg](https://c.tile.stamen.com/terrain/13/4305/2931.jpg)
[https://tile.stamen.com/terrain/13/4305/2932.jpg](https://tile.stamen.com/terrain/13/4305/2932.jpg)
[https://d.tile.stamen.com/terrain/13/4304/2931.jpg](https://d.tile.stamen.com/terrain/13/4304/2931.jpg)
[https://tile.stamen.com/terrain/13/4304/2932.jpg](https://tile.stamen.com/terrain/13/4304/2932.jpg)
[https://b.tile.stamen.com/terrain/13/4306/2931.jpg](https://b.tile.stamen.com/terrain/13/4306/2931.jpg)
[https://a.tile.stamen.com/terrain/13/4306/2932.jpg](https://a.tile.stamen.com/terrain/13/4306/2932.jpg)
[https://b.tile.stamen.com/terrain/13/4305/2930.jpg](https://b.tile.stamen.com/terrain/13/4305/2930.jpg)
[https://b.tile.stamen.com/terrain/13/4305/2933.jpg](https://b.tile.stamen.com/terrain/13/4305/2933.jpg)
[https://d.tile.stamen.com/terrain/13/4304/2930.jpg](https://d.tile.stamen.com/terrain/13/4304/2930.jpg)
[https://tile.stamen.com/terrain/13/4304/2933.jpg](https://tile.stamen.com/terrain/13/4304/2933.jpg)
[https://d.tile.stamen.com/terrain/13/4306/2930.jpg](https://d.tile.stamen.com/terrain/13/4306/2930.jpg)
[https://d.tile.stamen.com/terrain/13/4306/2933.jpg](https://d.tile.stamen.com/terrain/13/4306/2933.jpg)
[https://a.tile.stamen.com/terrain/13/4307/2931.jpg](https://a.tile.stamen.com/terrain/13/4307/2931.jpg)
[https://c.tile.stamen.com/terrain/13/4307/2932.jpg](https://c.tile.stamen.com/terrain/13/4307/2932.jpg)
[https://d.tile.stamen.com/terrain/13/4305/2934.jpg](https://d.tile.stamen.com/terrain/13/4305/2934.jpg)
[https://b.tile.stamen.com/terrain/13/4304/2934.jpg](https://b.tile.stamen.com/terrain/13/4304/2934.jpg)
[https://d.tile.stamen.com/terrain/13/4307/2930.jpg](https://d.tile.stamen.com/terrain/13/4307/2930.jpg)
[https://b.tile.stamen.com/terrain/13/4306/2933.jpg](https://a.tile.stamen.com/terrain/13/4307/2933.jpg)
[https://b.tile.stamen.com/terrain/13/4306/2934.jpg](https://b.tile.stamen.com/terrain/13/4306/2934.jpg)
[https://a.tile.stamen.com/terrain/13/4307/2934.jpg](https://a.tile.stamen.com/terrain/13/4307/2934.jpg)

Please fix this!
